[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_FIREBASE_API_KEY = "${VITE_FIREBASE_API_KEY}"
  VITE_FIREBASE_AUTH_DOMAIN = "${VITE_FIREBASE_AUTH_DOMAIN}"
  VITE_FIREBASE_PROJECT_ID = "${VITE_FIREBASE_PROJECT_ID}"
  VITE_FIREBASE_STORAGE_BUCKET = "${VITE_FIREBASE_STORAGE_BUCKET}"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "${VITE_FIREBASE_MESSAGING_SENDER_ID}"
  VITE_FIREBASE_APP_ID = "${VITE_FIREBASE_APP_ID}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200