[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDA6KX7eosWMga8D6oTTe3DlHLWwh0J634"
  VITE_FIREBASE_AUTH_DOMAIN = "simple-studio-a2535.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "simple-studio-a2535"
  VITE_FIREBASE_STORAGE_BUCKET = "simple-studio-a2535.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "424159773897"
  VITE_FIREBASE_APP_ID = "1:424159773897:web:6b855166ca5a9547187918"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200